### ISSUE TITLE
discount percentage

### ISSUE THREAD

**Issue by oscrx** [bierteam/Pils#19]
Implement logic to generate discount percentage

**Comment by NvdLaan** [comment]
Biernet already provides this information, so this can be scraped

**Comment by oscrx** [comment]
Easier to calculate then to trust biernet to not fuck up

Verstuurd vanaf mijn iPhone

**Comment by NvdLaan** [comment]
https://github.com/bierteam/Pils/commit/27162ead191c8a33509f87005516a4f04d59f684
