### ISSUE TITLE
Critical bug returned again

### ISSUE THREAD

**Issue by oscrx** [bierteam/Pils#27]
https://github.com/bierteam/Pils/commit/b09327c3755aacf779e657483aa8e198fea04e44
https://github.com/bierteam/Pils/commit/0529c094c489dffa13c88e2388a7dfba87e8a13c
![afbeelding](https://user-images.githubusercontent.com/6731096/48621784-f50d5480-e9a4-11e8-97cb-b0d896d9bd60.png)

**Comment by Mightybeardedking** [comment]
Won't apply for Dev version
